name: my_member_link
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.3
  http: ^1.2.2
  image_cropper: ^8.0.1
  image_picker: ^1.1.2
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
  - assets/images/
